import '@/features/popup/popup'
import 'layout/header/header.js'
import 'features/forms'
import 'ui/form/contact/contact.js'
import 'components/main-hero/main-hero.js'
import 'components/restaurant-block/restaurant-block.js'
import 'components/entertainment-block/entertainment-block.js'
import 'components/about/about.js'
